### ISSUE TITLE
Update homepage UI

### ISSUE THREAD

**Issue by rjayroso** [shrpereira/coviewer_flutter#14]
Hey, I 'm interested in your project and I was wondering if you want to upgrade your homepage UI.  The MaterialApp at the top looks like a search bar instead of a navigation bar which might confuse some users into thinking that the whole thing is clickable. My solution is to use an appBar that displays the app's title "Covid World Stats" and a clickable search bar that calls your  _showPickerModal(context, viewModel) function instead of clicking the tiny search icon. 

Let me know what you think, thanks!

**Comment by silviorp** [comment]
I haven't included the appBar in the app to bring a modern UI and to avoid it to have an Android UI, since the intention is to have it working both on Android and iOS. Also, I'm seeing a move from using the default Android appBar in most of the modern apps and I think that's happening because it looks too outdated.

I think removing the rounded rectangular background would be enough to eliminate the feel of a search bar from the top of the app. What do you think?

**Comment by rjayroso** [comment]
Oh I see what you were going for, and I totally agree now. Mind if I commit another to my PR and update it to keep the original design but remove the rounding?  
  
That being said, I still think you may need to display the country name at the top along with the flag since the title "Covid World Stats" for stats relating to only one country might be a little confusing. What do you think? Keep the title or make it dynamic in line with the country?
